config/routes.rb
Rails.application.routes.draw do
  get 'get_subjects_list/:id', to: 'qualifications#get_subjects_list', as: :get_subjects_list
  get 'get_products_list/:id', to: 'subjects#get_products_list', as: :get_products_list
  get 'get-all', to: 'exams#get_all', as: :getall
  post 'remove-all', to: 'exams#remove_all', as: :removeall
  resources :countries
  resources :subjects
  resources :qualifications
  resource :exams, only: [:index]
  get 'exams(/*other)', to: 'exams#index', as: :exams
  root 'exams#index'
end

app/models/qualification.rb
class Qualification < ActiveRecord::Base
  belongs_to :country
  has_many :subjects, through: :scientific_sets
  has_many :scientific_sets

  scope :not_empty, -> { where("subjects_count > 0").order(:country_id, :name) }
end

app/controllers/qualifications_controller.rb
class QualificationsController < ApplicationController
  before_action :set_qualification, only: [:show, :edit, :update, :destroy, :get_subjects_list]

  # GET /qualifications
  # GET /qualifications.json
  def index
    @qualifications = Qualification.all
  end

  # GET /qualifications/1
  # GET /qualifications/1.json
  def show
  end

  # GET /qualifications/new
  def new
    @qualification = Qualification.new
  end

  # GET /qualifications/1/edit
  def edit
  end

  # POST /qualifications
  # POST /qualifications.json
  def create
    @qualification = Qualification.new(qualification_params)

    respond_to do |format|
      if @qualification.save
        format.html { redirect_to @qualification, notice: 'Qualification was successfully created.' }
        format.json { render :show, status: :created, location: @qualification }
      else
        format.html { render :new }
        format.json { render json: @qualification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qualifications/1
  # PATCH/PUT /qualifications/1.json
  def update
    respond_to do |format|
      if @qualification.update(qualification_params)
        format.html { redirect_to @qualification, notice: 'Qualification was successfully updated.' }
        format.json { render :show, status: :ok, location: @qualification }
      else
        format.html { render :edit }
        format.json { render json: @qualification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qualifications/1
  # DELETE /qualifications/1.json
  def destroy
    @qualification.destroy
    respond_to do |format|
      format.html { redirect_to qualifications_url, notice: 'Qualification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_subjects_list
    @subjects = @qualification.subjects.order(:name)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qualification
      @qualification = Qualification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qualification_params
      params.require(:qualification).permit(:system_id, :name, :link, :country_id)
    end
end

app/helpers/qualifications_helper.rb
module QualificationsHelper
  def star_color(color)
    (color.blank? or color.nil?) ? "white" : color
  end
end

app/views/qualifications/_form.html.slim
= form_for @qualification, html: { class: "form form-horizontal qualification" } do |f|
  .form-group
    = f.label :system_id, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :system_id, :class => 'form-control'
    = f.error_span(:system_id)
  .form-group
    = f.label :name, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, :class => 'form-control'
    = f.error_span(:name)
  .form-group
    = f.label :link, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :link, :class => 'form-control'
    = f.error_span(:link)
  .form-group
    = f.label :country_id, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :country_id, :class => 'form-control'
    = f.error_span(:country_id)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), qualifications_path, :class => 'btn'
br
br

app/views/qualifications/_subjects.html.slim
ul.list-group
  li.list-group-item.active
    |Subjects
  - @subjects.each do |subject|
    li.list-group-item
      i.fa.fa-certificate style="color: #{star_color(subject.colour)};"
      |&nbsp;&nbsp;
      =link_to subject.name, get_products_list_path(subject), remote: true, class: "subject_link"

app/views/qualifications/edit.html.slim
- model_class = Qualification
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/qualifications/get_subjects_list.js.slim
| $("#subjects_list").html("#{escape_javascript(render 'subjects')}");
| $("#subjects_list").slideDown("slow");

app/views/qualifications/index.html.slim
- model_class = Qualification
.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th.table_id
        = model_class.human_attribute_name(:id)
      th.center
        = model_class.human_attribute_name(:name)
  tbody
    - @qualifications.each do |qualification|
      tr
        td= qualification.id
        td= link_to qualification.name, qualification_path(qualification)
br

app/views/qualifications/new.html.slim
- model_class = Qualification
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/qualifications/show.html.slim
- model_class = Qualification
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:system_id) + ':'
  br
  = @qualification.system_id
p
  strong= model_class.human_attribute_name(:name) + ':'
  br
  = @qualification.name
p
  strong= model_class.human_attribute_name(:link) + ':'
  br
  = @qualification.link
p
  strong= model_class.human_attribute_name(:country_id) + ':'
  br
  = @qualification.country_id

= link_to t('.back', :default => t("helpers.links.back")), qualifications_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_qualification_path(@qualification), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), qualification_path(@qualification), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'