config/routes.rb
Rails.application.routes.draw do
  get 'get_subjects_list/:id', to: 'qualifications#get_subjects_list', as: :get_subjects_list
  get 'get_products_list/:id', to: 'subjects#get_products_list', as: :get_products_list
  get 'get-all', to: 'exams#get_all', as: :getall
  post 'remove-all', to: 'exams#remove_all', as: :removeall
  resources :countries
  resources :subjects
  resources :qualifications
  resource :exams, only: [:index]
  get 'exams(/*other)', to: 'exams#index', as: :exams
  root 'exams#index'
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :qualifications, through: :scientific_sets
  has_many :scientific_sets

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy, :get_products_list]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # I just have no information about products/exams, so I take it randomly.
  def get_products_list
    @products = Array.new(rand(2..12), t(:some_product))
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:system_id, :title, :link, :icon, :colour)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.slim
= form_for @subject, html: { class: "form form-horizontal subject" } do |f|
  .form-group
    = f.label :system_id, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :system_id, :class => 'form-control'
    = f.error_span(:system_id)
  .form-group
    = f.label :name, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, :class => 'form-control'
    = f.error_span(:name)
  .form-group
    = f.label :link, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :link, :class => 'form-control'
    = f.error_span(:link)
  .form-group
    = f.label :icon, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :icon, :class => 'form-control'
    = f.error_span(:icon)
  .form-group
    = f.label :colour, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :colour, :class => 'form-control'
    = f.error_span(:colour)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), subjects_path, :class => 'btn'
br
br

app/views/subjects/_products.html.slim
ul.list-group
  li.list-group-item.active
    |Exams
  - @products.each_with_index do |product, idx|
    li.list-group-item
      |#{product} #{idx}

app/views/subjects/edit.html.slim
- model_class = Subject
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/subjects/get_products_list.js.slim
| $("#products_list").hide();
| $("#products_list").html("#{escape_javascript(render 'products')}");
| $("#products_list").slideDown("slow");

app/views/subjects/index.html.slim
- model_class = Subject
.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:colour)
  tbody
    - @subjects.each do |subject|
      tr
        td= subject.id
        td= link_to subject.name, subject_path(subject)
        td= subject.colour
br

app/views/subjects/new.html.slim
- model_class = Subject
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/subjects/show.html.slim
- model_class = Subject
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:system_id) + ':'
  br
  = @subject.system_id
p
  strong= model_class.human_attribute_name(:name) + ':'
  br
  = @subject.name
p
  strong= model_class.human_attribute_name(:link) + ':'
  br
  = @subject.link
p
  strong= model_class.human_attribute_name(:icon) + ':'
  br
  = @subject.icon
p
  strong= model_class.human_attribute_name(:colour) + ':'
  br
  = @subject.colour

= link_to t('.back', :default => t("helpers.links.back")), subjects_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_subject_path(@subject), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), subject_path(@subject), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'