config/routes.rb
Rails.application.routes.draw do
  get 'get_subjects_list/:id', to: 'qualifications#get_subjects_list', as: :get_subjects_list
  get 'get_products_list/:id', to: 'subjects#get_products_list', as: :get_products_list
  get 'get-all', to: 'exams#get_all', as: :getall
  post 'remove-all', to: 'exams#remove_all', as: :removeall
  resources :countries
  resources :subjects
  resources :qualifications
  resource :exams, only: [:index]
  get 'exams(/*other)', to: 'exams#index', as: :exams
  root 'exams#index'
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :qualifications

end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:code, :name, :link)
    end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_form.html.slim
= form_for @country, html: { class: "form form-horizontal country" } do |f|
  .form-group
    = f.label :code, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :code, :class => 'form-control'
    = f.error_span(:code)
  .form-group
    = f.label :name, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, :class => 'form-control'
    = f.error_span(:name)
  .form-group
    = f.label :link, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :link, :class => 'form-control'
    = f.error_span(:link)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), countries_path, :class => 'btn'

app/views/countries/edit.html.slim
- model_class = Country
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/countries/index.html.slim
- model_class = Country
.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th.table_id
        = model_class.human_attribute_name(:id)
      th.table_id
        = model_class.human_attribute_name(:code)
      th.center
        = model_class.human_attribute_name(:name)
  tbody
    - @countries.each do |country|
      tr
        td= link_to country.id, country_path(country)
        td= country.code
        td= country.name
br

app/views/countries/new.html.slim
- model_class = Country
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/countries/show.html.slim
- model_class = Country
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:code) + ':'
  br
  = @country.code
p
  strong= model_class.human_attribute_name(:name) + ':'
  br
  = @country.name
p
  strong= model_class.human_attribute_name(:link) + ':'
  br
  = @country.link

= link_to t('.back', :default => t("helpers.links.back")), countries_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_country_path(@country), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), country_path(@country), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'