config/routes.rb
Rails.application.routes.draw do
  get 'get_subjects_list/:id', to: 'qualifications#get_subjects_list', as: :get_subjects_list
  get 'get_products_list/:id', to: 'subjects#get_products_list', as: :get_products_list
  get 'get-all', to: 'exams#get_all', as: :getall
  post 'remove-all', to: 'exams#remove_all', as: :removeall
  resources :countries
  resources :subjects
  resources :qualifications
  resource :exams, only: [:index]
  get 'exams(/*other)', to: 'exams#index', as: :exams
  root 'exams#index'
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  def index
    @qualifications = Qualification.not_empty
  end

  def get_all
    ApiStore.get_all
    redirect_to root_path
  end

  def remove_all
    ApiStore.remove_all
    redirect_to root_path
  end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/index.html.slim
h1.center
  |Your exams? We've got them covered.
h4.center
  |Click a qualification below to see which subjects and exam boards are covered.
br
.row
  .col-md-4
    ul.list-group
      li.list-group-item.active
        |Qualifications
      - @qualifications.each do |qualification|
        li.list-group-item
          span.badge=qualification.subjects_count
          =link_to qualification.name, get_subjects_list_path(qualification), remote: true, class: "qualification_link"
  .col-md-4
    #subjects_list
  .col-md-4
    #products_list

javascript:
  $(document).ready(function() {
    $(".qualification_link").click(function () {
      $("#subjects_list").hide();
      $("#products_list").hide();
    });
  });